
// #include <stdio.h>
// #include <stdlib.h>

// int main()
// {
//     FILE* sample;
//     FILE* sequence;

//     sample = fopen("test_sample.txt", "w");
//     sequence = fopen("test_sequence.txt", "w");

//     fprintf(sample, "ACAAGATGCCATTGTCCCCCGGCCTCCTGCTGCTGCTGCTCTCCGGGGCCACGGCCACCGCTGCCCTGCCCCTGGAGGGTGGCCCCACCGGCCGAGACAGCGAGCATATGCAGGAAGCGGCAGGAATAAGGAAAAGCAGCCTCCTGACTTTCCTCGCTTGGTGGTTTGAGTGGACCTCCCAGGCCAGTGCCGGGCCCCTCATAGGAGAGGAAGCTCGGGAGGTGGCCAGGCGGCAGGAAGGCGCACCCCCCCAGCAATCCGCGCGCCGGGACAGAATGCCCTGCAGGAACTTCTTCTGGAAGACCTTCTCCTCCTGCAAATAAAACCTCACCCATGAATGCTCACGCAAGTTTAATTACAGACCTGAA\r\n");

//     fprintf(sequence, "GCCTCCTGCTGCTGCTGCTCTCC\r\n");
//     fprintf(sequence, "GGACCTCCCAGGCCAGTGCCGGG\r\n");
//     fprintf(sequence, "AAGACCTTCTCCTCCTGCAAATA\r\n");
//     fprintf(sequence, "TTCTTCTGGAAGACCTTCTCCTC\r\n");
//     fprintf(sequence, "CCAGGCGGCAGGAAGGCGCACCCCCCCAGCAATCCGTGCGCCGG\r\n");

//     fclose(sample);
//     fclose(sequence);
// }

